version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend/gui
    schedule:
      interval: "3 months"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: "3 months"
      day: "sunday"
      time: "16:00"
