# Generated by Django 2.1.4 on 2019-02-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0)),
                ('truckID', models.IntegerField(default=0)),
                ('itemName', models.CharField(max_length=100)),
                ('itemDescription', models.TextField(blank=True, null=True)),
                ('itemWeight', models.CharField(max_length=50)),
                ('occupiedArea', models.CharField(max_length=50)),
                ('urgencyRate', models.IntegerField(default=0)),
                ('itemImage', models.ImageField(blank=True, null=True, upload_to=None)),
                ('itemCategory', models.CharField(max_length=50)),
                ('deliveryDate', models.DateField(verbose_name='Conversation Date')),
                ('deliveryHour', models.CharField(max_length=50)),
                ('itemQuantity', models.IntegerField(default=1)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deliveryOrigin', models.CharField(max_length=50)),
                ('deliveryDestiny', models.CharField(max_length=50)),
                ('deliveryReceiver', models.CharField(max_length=100)),
                ('deliveryAddress', models.CharField(max_length=150)),
                ('paymentMethod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckStatus', models.BooleanField(default=False)),
                ('foodMaxQuantity', models.IntegerField(default=0)),
                ('officeMaterialMaxQuantity', models.IntegerField(default=0)),
                ('medicinesMaxQuantity', models.IntegerField(default=0)),
                ('carPartsMaxQuantity', models.IntegerField(default=0)),
                ('staffName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.IntegerField(default=0)),
                ('district', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('zipcode', models.CharField(max_length=50)),
            ],
        ),
    ]
