# Generated by Django 2.1.4 on 2019-02-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='itemWeight',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='occupiedArea',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
